function [Pv,Sigma] = NH_func(in1,Emod,nu)
%NH_func
%    [Pv,Sigma] = NH_func(IN1,Emod,NU)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Feb-2025 10:56:08

Fv1 = in1(1,:);
Fv2 = in1(2,:);
Fv3 = in1(3,:);
Fv4 = in1(4,:);
t2 = Fv1.^2;
t3 = Fv2.^2;
t4 = Fv3.^2;
t5 = Fv4.^2;
t6 = nu.*2.0;
t7 = nu+1.0;
t8 = Fv1.*Fv2;
t9 = Fv1.*Fv3;
t10 = Fv2.*Fv4;
t11 = Fv3.*Fv4;
t12 = t6+2.0;
t13 = -t11;
t14 = t6-1.0;
t15 = 1.0./t7;
t16 = t9+t10;
t17 = t2+t5;
t18 = t3+t4;
t19 = 1.0./t12;
t20 = t8+t13;
t21 = 1.0./t14;
t22 = log(t20);
t24 = 1.0./t20;
t23 = conj(t22);
t25 = t24.^2;
t26 = t17.*t25;
t27 = t18.*t25;
t30 = Emod.*t16.*t19.*t25;
t33 = Emod.*nu.*t15.*t16.*t21.*t22.*t25;
t38 = Emod.*nu.*t15.*t16.*t21.*t23.*t25;
t28 = t26-1.0;
t29 = t27-1.0;
t34 = Emod.*nu.*t15.*t21.*t22.*t26;
t35 = Emod.*nu.*t15.*t21.*t22.*t27;
t36 = Emod.*nu.*t15.*t21.*t23.*t26;
t37 = Emod.*nu.*t15.*t21.*t23.*t27;
t39 = t30+t33;
t40 = t30+t38;
t31 = Emod.*t19.*t28;
t32 = Emod.*t19.*t29;
t41 = Fv1.*t39;
t42 = Fv2.*t39;
t43 = Fv3.*t39;
t44 = Fv4.*t39;
t45 = t31+t34;
t46 = t32+t35;
t47 = t31+t36;
t48 = t32+t37;
Pv = [Fv3.*t40-Fv1.*t48;Fv4.*t40-Fv2.*t47;Fv1.*t40-Fv3.*t47;Fv2.*t40-Fv4.*t48];
if nargout > 1
    t49 = Fv1.*t46;
    t50 = Fv2.*t45;
    t51 = Fv3.*t45;
    t52 = Fv4.*t46;
    t53 = -t49;
    t54 = -t50;
    t55 = -t51;
    t56 = -t52;
    t57 = t41+t55;
    t58 = t43+t53;
    t59 = t42+t56;
    t60 = t44+t54;
    Sigma = reshape([t24.*(Fv1.*t58+Fv3.*t57),t24.*(Fv1.*t59+Fv3.*t60),0.0,t24.*(Fv2.*t57+Fv4.*t58),t24.*(Fv2.*t60+Fv4.*t59),0.0,0.0,0.0,-Emod.*nu.*t15.*t21.*t22.*t24],[3,3]);
end
end
